import callsModal from './modules/callsModal';
import pageOrientation from './modules/pageOrientation';
import accordeon from './modules/accordeon';
import swiper from './modules/swiper';
import slider from './modules/slider';
import modal from './modules/modal';
callsModal();
pageOrientation();
accordeon();
swiper();
slider();
modal();